"""
    SafeMTA Error Exceptions
"""

class MaxMapNameLength              (Exception): ...
class MaxGameTypeLength             (Exception): ...
class MySQLUnkownError              (Exception): ...
class MySQLConnectionDetected       (Exception): ...
class SQLQueryUnkownConditionType   (Exception): ...
class MySQLNoConnection             (Exception): ...
class ServerNotRunning              (Exception): ...
class SQLite3NullPath               (Exception): ...
class SQLite3ConnectionDetected     (Exception): ...
class SQLite3NoConnection           (Exception): ...
class SQLite3UnkownError            (Exception): ...
class SettingsLoading               (Exception): ...
class SettingsFile                  (Exception): ...
class InvalidPortNumber             (Exception): ...
class ServerNetworkingError         (Exception): ...
class NetWrapperLoadingError        (Exception): ...
class NetWrapperVersionError        (Exception): ...
class NetWrapperInterfaceError      (Exception): ...
class NetWrapperInitError           (Exception): ...
class NetWrapperStartError          (Exception): ...
class ResourceFileError             (Exception): ...
class BitStreamError                (Exception): ...
