"""
    PyMTA Error Exceptions
"""

class MaxMapNameLength              (Exception): ...
class MaxGameTypeLength             (Exception): ...
class MySQLUnkownError              (Exception): ...
class MySQLConnectionDetected       (Exception): ...
class SQLQueryUnkownConditionType   (Exception): ...
class MySQLNoConnection             (Exception): ...
class ServerNotRunning              (Exception): ...
class SQLite3NullPath               (Exception): ...
class SQLite3ConnectionDetected     (Exception): ...
class SQLite3NoConnection           (Exception): ...
class SQLite3UnkownError            (Exception): ...
class SettingsLoading               (Exception): ...
class ServerNetworkingError         (Exception): ...
