MIN_PLAYER_NICK_LENGTH = 1
MAX_PLAYER_NICK_LENGTH = 22
MIN_PLAYER_NAMETAG_LENGTH = 1
MAX_PLAYER_NAMETAG_LENGTH = 64
MAX_SERIAL_LENGTH = 32

MAX_TEAM_NAME_LENGTH = 255
MIN_PASSWORD_LENGTH = 1

MIN_CHAT_LENGTH = 1
MAX_CHAT_LENGTH = 255

MIN_COMMAND_LENGTH = 1
MAX_COMMAND_LENGTH = 255

MIN_OUTPUTCHATBOX_LENGTH = 1
MAX_OUTPUTCHATBOX_LENGTH = 1

MAX_MAP_NAME_LENGTH = 200
MAX_ASE_MAP_NAME_LENGTH = 200
MAX_RULE_KEY_LENGTH = 200
MAX_RULE_VALUE_LENGTH = 200
MAX_ASE_GAME_TYPE_LENGTH = 200
MAX_HTTP_DOWNLOAD_URL = 512
